# Generated by Django 5.2.5 on 2025-08-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country_of_origin",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
