# Generated by Django 5.2.5 on 2025-08-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_conversation_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_avatars/"
            ),
        ),
    ]
