# Generated by Django 4.2.23 on 2025-08-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='accounts_me_is_read_ad2c8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block_pair'),
        ),
    ]
